version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_DB=mussum"
      - "POSTGRES_PASSWORD=password"
    expose:
      - "5432"
    ports:
      - "5432:5432"